---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-amf-466-93
  labels:
    app: free5gc-amf-466-93
spec:
  replicas: 1
  selector:
    matchLabels:
      app: free5gc-amf-466-93
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: free5gc-amf-466-93
        nsi: "1"
        mcc: "466"
        mnc: "93"
        telecom: TWM
      annotations:
        k8s.v1.cni.cncf.io/networks: free5gc-macvlan
        free5gc-macvlan.free5gc.kubernetes.io/ip_address: 192.168.72.54
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: free5gc-amf
          image: black842679513/free5gc-amf:v3.0.5
          imagePullPolicy: IfNotPresent
          # imagePullPolicy: Always
          securityContext:
            privileged: false
          volumeMounts:
            - name: free5gc-amf-466-93-config
              mountPath: /free5gc/config
            - name: free5gc-amf-466-93-cert
              mountPath: /free5gc/support/TLS
          ports:
            - containerPort: 8000
              name: free5gc-amf
              protocol: TCP
            - containerPort: 38412
              name: if-n1n2
              protocol: SCTP
        - name: tcpdump
          image: corfr/tcpdump
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sleep
            - infinity
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: free5gc-amf-466-93-sa
      terminationGracePeriodSeconds: 30
      volumes:
        - name: free5gc-amf-466-93-cert
          secret:
            secretName: free5gc-amf-466-93-tls-secret
        - name: free5gc-amf-466-93-config
          configMap:
            name: free5gc-amf-466-93-config
