---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: free5gc-amf-466-93
  name: free5gc-amf-466-93
spec:
  # type: ClusterIP
  # type: NodePort
  clusterIP: None
  ports:
  - name: free5gc-amf
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: if-n1n2
    port: 38412
    protocol: SCTP
    targetPort: 38412
  #  nodePort: 32150
  selector:
    app: free5gc-amf-466-93
