---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: free5gc-webui-466-93
  name: free5gc-webui-466-93
spec:
  type: NodePort
  ports:
  - name: free5gc-webui
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: free5gc-webui-466-93
