---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: free5gc-mongodb-466-93
  name: free5gc-mongodb-466-93
spec:
  clusterIP: None
  ports:
  - name: free5gc-mongodb
    port: 27017
    targetPort: 27017
    protocol: TCP
  selector:
    app: free5gc-mongodb-466-93
