---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: free5gc
resources:
  - smf-sa.yaml
  - smf-rbac.yaml
  - smf-service.yaml
  - smf-deployment.yaml

# declare Secret from a secretGenerator
secretGenerator:
- name: free5gc-smf-tls-secret
  namespace: free5gc
  files:
  - TLS/smf.pem
  - TLS/smf.key
  type: "Opaque"
generatorOptions:
  disableNameSuffixHash: true

# declare ConfigMap from a ConfigMapGenerator
configMapGenerator:
- name: free5gc-smf-config
  namespace: free5gc
  files:
    - config/smfcfg.yaml
    - config/uerouting.yaml
