---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
patchesStrategicMerge:
- pod-affinity.yaml

# declare ConfigMap from a ConfigMapGenerator
configMapGenerator:
- name: free5gc-smf-config
  namespace: free5gc
  behavior: replace
  files:
    - config/smfcfg.yaml
    - config/uerouting.yaml
