---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: free5gc-smf
  name: free5gc-smf
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                # - free5gc-gnbsim
                - free5gc-ueransim-gnb
            topologyKey: "kubernetes.io/hostname"
