{
 "title": "network-slice-service",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Resource Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (kube_pod_labels{label_app=~\"service.*\"} * on (pod) group_right(label_app) kube_pod_container_resource_limits_cpu_cores) OR vector(0)",
     "legendFormat": "{{label_app}}"
    }
   ]
  },
  {
   "title": "Tenant 466-01 Resource Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (kube_pod_labels{label_app=~\"service-466-01-000000010-0x0101.*\"} * on (pod) group_right(label_app) kube_pod_container_resource_limits_cpu_cores) by (label_app) OR vector(0)",
     "legendFormat": "{{label_app}}"
    },
    {
     "expr": "sum (kube_pod_labels{label_app=~\"service-466-01-000000010-0x0101.*\"} * on (pod) group_right(label_app) rate(container_cpu_usage_seconds_total{container!=\"\"}[10s])) OR vector(0)"
    }
   ]
  },
  {
   "title": "Tenant 466-11 Resource Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (kube_pod_labels{label_app=~\"service-466-11-000000010-0x0102.*\"} * on (pod) group_right(label_app) kube_pod_container_resource_limits_cpu_cores) by (label_app) OR vector(0)",
     "legendFormat": "{{label_app}}"
    },
    {
     "expr": "sum (kube_pod_labels{label_app=~\"service-466-11-000000010-0x0102.*\"} * on (pod) group_right(label_app) rate(container_cpu_usage_seconds_total{container!=\"\"}[10s])) OR vector(0)",
     "legendFormat": "{{label_app}}"
    }
   ]
  },
  {
   "title": "Tenant 466-93 Resource Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (kube_pod_labels{label_app=~\"service-466-93-000000010-0x0103.*\"} * on (pod) group_right(label_app) kube_pod_container_resource_limits_cpu_cores) by (label_app) OR vector(0)",
     "legendFormat": "{{label_app}}"
    },
    {
     "expr": "sum (kube_pod_labels{label_app=~\"service-466-93-000000010-0x0103.*\"} * on (pod) group_right(label_app) rate(container_cpu_usage_seconds_total{container!=\"\"}[10s])) OR vector(0)",
     "legendFormat": "{{label_app}}"
    }
   ]
  }
 ]
}