---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: free5gc
resources:
  - nrf-sa.yaml
  - nrf-rbac.yaml
  - nrf-service.yaml
  - nrf-deployment.yaml

# declare Secret from a secretGenerator
secretGenerator:
- name: free5gc-nrf-466-01-tls-secret
  namespace: free5gc
  files:
  - TLS/nrf.pem
  - TLS/nrf.key
  type: "Opaque"
generatorOptions:
  disableNameSuffixHash: true

# declare ConfigMap from a ConfigMapGenerator
configMapGenerator:
- name: free5gc-nrf-466-01-config
  namespace: free5gc
  files:
    - config/nrfcfg.yaml
