---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: free5gc
resources:
  - ueransim-ue-0x01010203-sa.yaml
  - ueransim-ue-0x01010203-rbac.yaml
  - ueransim-ue-0x01010203-deployment.yaml

# declare ConfigMap from a ConfigMapGenerator
configMapGenerator:
- name: free5gc-ueransim-ue-0x01010203-config
  namespace: free5gc
  files:
    - config/free5gc-ue.yaml
   # - config/free5gc-ue-test.yaml
   # - config/free5gc-ue-test1.yaml
    - config/free5gc-ue-466-01.yaml
