---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: gnbs.nso.free5gc.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: nso.free5gc.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                mcc:
                  type: string
                mnc:
                  type: string
                ue-nums:
                  type: integer
                n3_cidr:
                  type: string
                external_ip:
                  type: string
      # print column of crd
      additionalPrinterColumns:
        - name: MCC
          type: string
          jsonPath: .spec.mcc
        - name: MNC
          type: string
          jsonPath: .spec.mnc
        - name: UE Numbers
          type: integer
          jsonPath: .spec.ue-nums
        - name: N3 CIDR
          type: string
          jsonPath: .spec.n3_cidr
        - name: External IP
          type: string
          jsonPath: .spec.external_ip
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: gnbs
    # singular name to be used as an alias on the CLI and for display
    singular: gnb
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: gNB
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - gnb

