---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: telecoms.nso.free5gc.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: nso.free5gc.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                id:
                  type: integer
                provider:
                  type: string
                abbrev:
                  type: string
                mcc:
                  type: string
                mnc:
                  type: string
                gnb-nums:
                  type: integer
                slice-nums:
                  type: integer
      # print column of crd
      additionalPrinterColumns:
        - name: ID
          type: integer
          description: The cron spec defining the interval a CronJob is run
          jsonPath: .spec.id
        - name: PROVIDER
          type: string
          jsonPath: .spec.provider
        - name: Abbrev
          type: string
          jsonPath: .spec.abbrev
        - name: MCC
          type: string
          jsonPath: .spec.mcc
        - name: MNC
          type: string
          jsonPath: .spec.mnc
        - name: gNB Numbers
          type: integer
          jsonPath: .spec.gnb-nums
        - name: Slice Numbers
          type: integer
          jsonPath: .spec.slice-nums
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: telecoms
    # singular name to be used as an alias on the CLI and for display
    singular: telecom
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: TeleCom
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - tc
