---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: free5gc
resources:
  - network-attachment-definition/free5gc-n3-208-93-000000010.yaml
  - subnet/free5gc-n3-208-93-000000010.yaml
  - ueransim-gnb-sa.yaml
  - ueransim-gnb-rbac.yaml
  - ueransim-gnb-service.yaml
  - ueransim-gnb-deployment.yaml
  - config/free5gc-gnb-208-93-000000010.yaml

# declare ConfigMap from a ConfigMapGenerator
#configMapGenerator:
#- name: free5gc-ueransim-gnb-config
#  namespace: free5gc
#  files:
#    - config/free5gc-gnb.yaml
#    - config/free5gc-gnb1.yaml
