---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: free5gc-udm-466-11
  name: free5gc-udm-466-11
spec:
  type: ClusterIP
  ports:
  - name: free5gc-udm
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: free5gc-udm-466-11
