---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: free5gc-smf
  name: free5gc-smf
spec:
  type: ClusterIP
  ports:
  - name: free5gc-smf-sbi
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: free5gc-smf-n4
    port: 8805
    protocol: UDP
    targetPort: 8805
  selector:
    app: free5gc-smf
