---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: free5gc-smf
  labels:
    app: free5gc-smf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: free5gc-smf
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: free5gc-smf
      annotations:
        k8s.v1.cni.cncf.io/networks: free5gc-smf-n4
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: free5gc-smf
          image: black842679513/free5gc-smf:v3.0.5
          imagePullPolicy: IfNotPresent
          # imagePullPolicy: Always
          securityContext:
            privileged: false
          volumeMounts:
            - name: free5gc-smf-config
              mountPath: /free5gc/config
            - name: free5gc-smf-cert
              mountPath: /free5gc/support/TLS
          ports:
            - containerPort: 8000
              name: if-sbi
              protocol: TCP
            - containerPort: 8805
              name: if-n4
              protocol: UDP
        - name: tcpdump
          image: corfr/tcpdump
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sleep
            - infinity
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: free5gc-smf-sa
      terminationGracePeriodSeconds: 30
      volumes:
        - name: free5gc-smf-cert
          secret:
            secretName: free5gc-smf-tls-secret
        - name: free5gc-smf-config
          configMap:
            name: free5gc-smf-config
