---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: free5gc
resources:
  - ausf-sa.yaml
  - ausf-rbac.yaml
  - ausf-service.yaml
  - ausf-deployment.yaml

# declare Secret from a secretGenerator
secretGenerator:
- name: free5gc-ausf-466-93-tls-secret
  namespace: free5gc
  files:
  - TLS/ausf.pem
  - TLS/ausf.key
  type: "Opaque"
generatorOptions:
  disableNameSuffixHash: true

# declare ConfigMap from a ConfigMapGenerator
configMapGenerator:
- name: free5gc-ausf-466-93-config
  namespace: free5gc
  files:
    - config/ausfcfg.yaml
