---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: free5gc-nssf
  name: free5gc-nssf
spec:
  type: ClusterIP
  ports:
  - name: free5gc-nssf
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: free5gc-nssf
