---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongodb-466-11-pv-volume
  labels:
    type: local
    namespace: free5gc
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    type: DirectoryOrCreate
    path: /mnt/dbdata-466-11
