---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: free5gc-ueransim-gnb
  name: free5gc-ueransim-gnb
spec:
  type: ClusterIP
  ports:
  - name: free5gc-ueransim-gnb-n3
    port: 2152
    protocol: UDP
    targetPort: 2152
  selector:
    app: free5gc-ueransim-gnb
