---
apiVersion: "nssmf.free5gc.com/v1"
kind: NetworkSlice
metadata:
  name: "0x0103020b"
  namespace: free5gc
  labels:
    nsi: "1"
    mcc: "466"
    mnc: "93"
    telecom: TWM
spec:
  sst: "01"
  sd: "03020b"
  status: Inactive
  n4_cidr: Undefined
  ue_subnet: Undefined
  cpu: Default
  memory: Default
  bandwidth: Default
