---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: free5gc-upf-1
  name: free5gc-upf-1
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - free5gc-gnbsim
            topologyKey: "kubernetes.io/hostname"
