---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qos-test
resources:
  - qos-test.yaml
  - NetworkAttachmentDefinition/qos-nic-1.yaml
  - NetworkAttachmentDefinition/qos-nic-2.yaml
  - qos-nic-1.yaml
  - qos-nic-2.yaml
  - bandwidth-test-iperf-server.yaml
  - bandwidth-test-iperf-client.yaml
