---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: free5gc
resources:
  - nssf-sa.yaml
  - nssf-rbac.yaml
  - nssf-service.yaml
  - nssf-deployment.yaml

# declare Secret from a secretGenerator
secretGenerator:
- name: free5gc-nssf-466-11-tls-secret
  namespace: free5gc
  files:
  - TLS/nssf.pem
  - TLS/nssf.key
  type: "Opaque"
generatorOptions:
  disableNameSuffixHash: true

# declare ConfigMap from a ConfigMapGenerator
configMapGenerator:
- name: free5gc-nssf-466-11-config
  namespace: free5gc
  files:
    - config/nssfcfg.yaml
