---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: free5gc
resources:
  - vppagent-firewall-nse.yaml
  - vppagent-passthrough-nse.yaml
  - vpn-gateway-nse.yaml
  - secure-intranet-connectivity.yaml
